services:
  timescaledb:
    container_name: timescaledb
    image: timescale/timescaledb:latest-pg14
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=timescaledb
    volumes:
      - timescale-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    network_mode: host

  optunadb:
    container_name: optunadb
    image: postgres:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=optimization_database
    volumes:
      - optuna-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo-db-data:/data/db
    network_mode: host

volumes:
  timescale-data:
    driver: local
  optuna-data:
    driver: local
  mongo-db-data:
    driver: local